# This workflow deploys a preview environment for your application to Okteto.

name: Okteto Preview Deployment

# Controls when the action will run. 
on: 
  pull_request:
    branches:
      - main

jobs:

  devflow:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
      
    - uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
        url: ${{ secrets.OKTETO_URL }}
        
    - name: "Deploy the previews preview environment"
      uses: okteto/deploy-preview@master
      with:
        name: pr-env-youngestdev
